### ISSUE TITLE
Error when adding repository

### ISSUE THREAD

**Issue by arnib13** [spocon/spocon#11]
**Describe the bug**
I get an error when following the Launchpad directions

**To Reproduce**
1. Go to terminal and enter: "sudo add-apt-repository ppa:spocon/spocon"
2. See error:
"Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/stretch"

**Expected behavior**
Should add repo and then install. 

**Desktop (please complete the following information):**
Raspbian 9.11 strech on RPI3

**Comment by spocon** [comment]
That script is for Ubuntu and Debian , for Raspberry PI you just execute this in a terminal:

curl -sL https://spocon.github.io/spocon/install.sh | sh

**Comment by arnib13** [comment]
Thanks!
