### ISSUE TITLE
NullPointerException in StateWrapper.java

### ISSUE THREAD

**Issue by mouse256** [spocon/spocon#26]
**Describe the bug**
A NullPointerexception was thrown while trying to connect

**To Reproduce**
Does not happen all the time
1. Another account was connected to the spocon instance first, but stopped playing
2. I try to connect from another account and another phone
3. I end up with the crash.

**Logs**
`2021-02-13 11:13:55,178 DEBUG Player:293 - Received command: Pause
2021-02-13 11:13:55,180 DEBUG DealerClient:109 - Handled request. {key: fa767c9d-bbdf-xxxx-8266-e3caae86316b, result: SUCCESS}
2021-02-13 11:13:55,736 INFO  DeviceStateHandler:252 - Put state. {ts: 1613211235178, connId: NmE4N...GOUZD, reason: PLAYER_STATE_CHANGED}
2021-02-13 11:17:15,496 INFO  StateWrapper:321 - Notified inactivity!
2021-02-13 11:17:16,053 INFO  DeviceStateHandler:252 - Put state. {ts: 1613211435494, connId: NmE4N...GOUZD, reason: BECAME_INACTIVE}
2021-02-13 11:47:33,267 DEBUG PlayerQueueEntry:209 - PlayerQueueEntry{0129efd386c2f3200757b11fffb188e5} has been removed from output.
2021-02-13 11:47:33,273 INFO  Session:416 - Closing session. {deviceId: 6a854[xxx]c740dc}
2021-02-13 11:47:33,278 DEBUG DealerClient:319 - Did not dispatch connection invalidated: null != xyz.gianlu.librespot.dealer.DealerClient$ConnectionHolder@24bc623a
2021-02-13 11:47:33,526 DEBUG EventService:35 - Event sent. {body: 12|37|67|6a854[xxx]c740dc|0129efd386c2f3200757b11fffb188e5|00000000000000000000000000000000|playlist|trackdone|unknown|logout|786432|5392812|-1694450033|-1694450033|278386|6|0|0|0|0|0|0|-1|context|-1|0|1|0|0|0|-1694450033|-1694450033|0|176400|spotify:user:4c4dc6l4563sw42sbpjn5bi6o:playlist:0ryJqtAalcQFM3ryHiOlVx|vorbis|41d8db30b70948028970f4e09e946897||0|1613211219806|0|context|home|8.6.0.830|com.spotify|crossfade|none|9b2096e8d94e1fc609877cddf8ce3deaf26e7161|na|none, result: 200}
2021-02-13 11:47:33,747 DEBUG EventService:35 - Event sent. {body: 10|20|34f1986baece6327b92009c81abcb95cb5ee7ddd|0129efd386c2f3200757b11fffb188e5|0|0|0|0|0|0|786432|5392812|music|-1|-1|-1|-1.000000|-1|-1.000000|-1|-1|-1|-1.000000|-1|-1|-1|-1|-1.000000|-1|0.000000|-1.000000|||unknown|0|0|0|0|0|interactive|0|176400|0|0, result: 200}
2021-02-13 11:47:33,967 DEBUG EventService:35 - Event sent. {body: 372|1|0129efd386c2f3200757b11fffb188e5|spotify:track:20fBuVybkHgjF6vNhSMROD|0|[[0,-1694450033]], result: 200}
2021-02-13 11:47:33,972 INFO  Session:475 - Closed session. {deviceId: 6a854[xxx]c740dc}
2021-02-13 11:47:33,973 INFO  ZeroconfServer:328 - Accepted new user from Nokia T. {deviceId: 6a854[xxx]c740dc}
2021-02-13 11:47:34,023 DEBUG TimeProvider:74 - Loaded time offset from NTP: -2ms
2021-02-13 11:47:34,078 INFO  Session:120 - Created new session! {deviceId: 6a854[xxx]c740dc, ap: gew1-accesspoint-e-d75b.ap.spotify.com:80, proxy: false}
2021-02-13 11:47:34,421 INFO  Session:310 - Connected successfully!
2021-02-13 11:47:34,484 INFO  Session:1362 - Skipping SecretBlock
2021-02-13 11:47:34,484 INFO  Session:1334 - Received LicenseVersion: 0
2021-02-13 11:47:34,484 DEBUG TokenProvider:51 - Token expired or not suitable, requesting again. {scopes: [playlist-read], oldToken: null}
2021-02-13 11:47:34,485 INFO  Session:1324 - Received CountryCode: BE
2021-02-13 11:47:34,497 INFO  CacheManager:80 - There are 61 cached entries.
2021-02-13 11:47:34,526 INFO  Session:1362 - Skipping LegacyWelcome
2021-02-13 11:47:34,526 INFO  Session:1362 - Skipping UnknownData_AllZeros
2021-02-13 11:47:34,527 DEBUG MercuryClient:218 - Couldn't dispatch Mercury event {seq: -653555209108193280, uri: hm://pusher/v1/connections/NmE4NTQwZDI5NzIwZmZiMGNiYjBjOTBjZjVmN2YzZjY2NGM3NDBkYytBUCt0Y3A6Ly9nZXcxLWFjY2Vzc3BvaW50LWUtZDc1Yi5nZXcxLnNwb3RpZnkubmV0OjUwMjYrOUExNkQwQTE4MThDODk0M0Y1Qzc1ODM1QjE2RTEyMEU3QkU5NUI3MDFFNTYzRUFGRjM5ODgwNTE1NkQ1NENGMg%3D%3D, code: 200, payload: []}
2021-02-13 11:47:34,528 DEBUG Session:1338 - Received 0x10: 4F23473327B3C7A1CF9989FA062A49EAB2918042
2021-02-13 11:47:34,563 INFO  Session:1289 - Skipping unknown command {cmd: 0x75, payload: 000000}
2021-02-13 11:47:34,564 DEBUG EventService:35 - Event sent. {body: 812|1|en, result: 200}
2021-02-13 11:47:34,565 DEBUG TokenProvider:55 - Updated token successfully! {scopes: [playlist-read], newToken: StoredToken{expiresIn=3600, accessToken='BQBKL7...NYnivs', scopes=[playlist-read], timestamp=1613213254562}}
2021-02-13 11:47:34,566 INFO  Session:341 - Authenticated as mouse256!
2021-02-13 11:47:34,681 DEBUG DealerClient:331 - Dealer connected! {host: gew-dealer.spotify.com}
2021-02-13 11:47:34,685 DEBUG DeviceStateHandler:135 - Updated Spotify-Connection-Id: NmE4NTQ[xx]5REEzMTlC
2021-02-13 11:47:34,688 INFO  StateWrapper:301 - Notified new device (us)!
2021-02-13 11:47:34,836 INFO  DeviceStateHandler:252 - Put state. {ts: 1613213254684, connId: NmE4N...zMTlC, reason: NEW_DEVICE}
2021-02-13 11:47:35,080 DEBUG Player:293 - Received command: Transfer
2021-02-13 11:47:35,089 DEBUG Player:365 - Loading context (transfer), uri: spotify:station:playlist:0ryJqtAalcQFM3ryHiOlVx
2021-02-13 11:47:35,090 ERROR DealerClient:112 - Failed handling request. {key: 757694cc-15f0-xxxx-acac-28fbf8dc65ce}
java.lang.NullPointerException: null
	at xyz.gianlu.librespot.player.StateWrapper.setShufflingContext(StateWrapper.java:154) ~[librespot-java-api-v1.5.4.jar:1.5.4]
	at xyz.gianlu.librespot.player.StateWrapper.setContext(StateWrapper.java:254) ~[librespot-java-api-v1.5.4.jar:1.5.4]
	at xyz.gianlu.librespot.player.StateWrapper.transfer(StateWrapper.java:472) ~[librespot-java-api-v1.5.4.jar:1.5.4]
	at xyz.gianlu.librespot.player.Player.handleTransferState(Player.java:368) ~[librespot-java-api-v1.5.4.jar:1.5.4]
	at xyz.gianlu.librespot.player.Player.command(Player.java:300) ~[librespot-java-api-v1.5.4.jar:1.5.4]
	at xyz.gianlu.librespot.player.state.DeviceStateHandler.notifyCommand(DeviceStateHandler.java:110) ~[librespot-java-api-v1.5.4.jar:1.5.4]
	at xyz.gianlu.librespot.player.state.DeviceStateHandler.onRequest(DeviceStateHandler.java:176) ~[librespot-java-api-v1.5.4.jar:1.5.4]
	at xyz.gianlu.librespot.dealer.DealerClient.lambda$handleRequest$1(DealerClient.java:107) ~[librespot-java-api-v1.5.4.jar:1.5.4]
	at xyz.gianlu.librespot.common.AsyncWorker.lambda$new$0(AsyncWorker.java:20) ~[librespot-java-api-v1.5.4.jar:1.5.4]
	at xyz.gianlu.librespot.common.AsyncProcessor.lambda$submit$1(AsyncProcessor.java:40) ~[librespot-java-api-v1.5.4.jar:1.5.4]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
`

Spocon is running on raspberry-pi, java-corretto-11.
Up-to-date with latest version.

**Comment by devgianlu** [comment]
Fixed this on the main repo and released version [1.5.5](https://github.com/librespot-org/librespot-java/releases/tag/v1.5.5).

**Comment by mouse256** [comment]
Cool thanks.

**Comment by spocon** [comment]
@mouse256 upgrade should be now available.

**Comment by mouse256** [comment]
I did. Shall I close this ticket then?
I'll reopen a new one if I see it again.
