### ISSUE TITLE
Spocon fails to connect after a long time running

### ISSUE THREAD

**Issue by mouse256** [spocon/spocon#37]
When spocon is running for a long time (like weeks), I sometimes encounter that it fails with traces like this:
```
2021-06-24 22:08:08,992 ERROR Session:730 - Failed reconnecting, retrying in 10 seconds...
java.net.UnknownHostException: gew1-accesspoint-d-xnwh.ap.spotify.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
        at java.net.Socket.connect(Socket.java:609) ~[?:?]
        at java.net.Socket.connect(Socket.java:558) ~[?:?]
        at java.net.Socket.<init>(Socket.java:454) ~[?:?]
        at java.net.Socket.<init>(Socket.java:231) ~[?:?]
        at xyz.gianlu.librespot.core.Session$ConnectionHolder.create(Session.java:1242) ~[librespot-java-api-v1.6.0.jar:1.6.0]
        at xyz.gianlu.librespot.core.Session.reconnect(Session.java:712) ~[librespot-java-api-v1.6.0.jar:1.6.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```
It keeps on printing this error.

That host effectively does not exist anymore. Maybe because of redeploys at the spotify server side some loadbalancer names changed?

When I just restart spocon, it discovers a new list of accesspoint urls (the old one is not in that list anymore) and works like a charm.

**Comment by devgianlu** [comment]
I think that retrieving a new list before trying to reconnect should do the job. See https://github.com/librespot-org/librespot-java/commit/591fb92db5931d611779ab83f9747f4decaea3f7

**Comment by spocon** [comment]
this should be fixed with the new version
