### ISSUE TITLE
Spocon stopped working -- librespot-java upgrade required

### ISSUE THREAD

**Issue by miniworm** [spocon/spocon#57]
Few days ago my spocon server (running on Ubuntu 20.04 x64) stopped working - on smartphone client was showing endless "connecting" status.
After digging in the logs I've found message:

> xyz.gianlu.librespot.core.Session$SpotifyAuthenticationException: PremiumAccountRequired

All of this without any changes on servers side and on my smartphone for months.

Then I've discovered that recently Spotify has changed something in login process and this is the reason of whole issue. It was already (2 days ago) addressed in librespot-java version 1.6.3 - https://github.com/librespot-org/librespot-java/releases/tag/v1.6.3

So there is a urgent need to bump librespot-java and naturally whole spocon package (I use it from Ubuntu PPA).

**Comment by aedeny** [comment]
Here's the full error message:

```
2023-05-20 10:15:15,950 ERROR ZeroconfServer:375 - Couldn't establish a new session.
xyz.gianlu.librespot.core.Session$SpotifyAuthenticationException: PremiumAccountRequired
        at xyz.gianlu.librespot.core.Session.authenticatePartial(Session.java:450) ~[librespot-java-api-v1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.core.Session.authenticate(Session.java:339) ~[librespot-java-api-v1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.core.Session.access$600(Session.java:77) ~[librespot-java-api-v1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.core.Session$Builder.create(Session.java:1029) ~[librespot-java-api-v1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.ZeroconfServer.handleAddUser(ZeroconfServer.java:367) ~[librespot-java-api-v1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.ZeroconfServer.access$200(ZeroconfServer.java:56) ~[librespot-java-api-v1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.handleRequest(ZeroconfServer.java:499) ~[librespot-java-api-v1.6.>
        at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:574) ~[librespot-java-api-v1.6.2.jar:1>
        at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:482) ~[librespot-java-api-v1.6.2>
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by avantgarden** [comment]
I have the same issue on Ubuntu 22.04 on aarch64 (RPI 4).

**Comment by miniworm** [comment]
For me the working fix was to replace /opt/spocon/librespot-java-api-v1.6.2.jar with https://github.com/librespot-org/librespot-java/releases/download/v1.6.3/librespot-api-1.6.3.jar (changing filename to old librespot-java-api-v1.6.2.jar so startup script works without changes. Now everything is as it was earlier.
You may apply similar approach to your setup until new spocon package will be released.

**Comment by PaulKierstead** [comment]
> For me the working fix was to replace /opt/spocon/librespot-java-api-v1.6.2.jar with https://github.com/librespot-org/librespot-java/releases/download/v1.6.3/librespot-api-1.6.3.jar (changing filename to old librespot-java-api-v1.6.2.jar so startup script works without changes). Now everything is as it was earlier. You may apply similar approach to your setup until new spocon package will be released.

Awesome, worked here nicely, ty!

**Comment by chdefrene** [comment]
If you're running the Docker image, here's how to fix it until a new tag is pushed.

Download the `v1.6.3` from above and add the following volume mapping:
```yaml
volumes:
      - librespot-api-1.6.3.jar:/opt/librespot/app.jar
```

**Comment by floodwayprintco** [comment]
> 

This worked for me, too. THANK YOU!

I had some trouble because I didn't notice the differences in the filename. Maybe that will help someone else.

Bonus: I updated my Owntone server as part of troubleshooting which was unnecessary, but it's way more responsive than old Forked-Daapd was. Very worth it and way easier than I expected.

**Comment by spocon** [comment]
new version should fix this issue: 1.6.3 released

**Comment by floodwayprintco** [comment]
> 

Do you think I should do this update if I already made the manual fix myself? 

Sorry if this is the wrong place for the question.

**Comment by spocon** [comment]
Hi, no its not needed

**Comment by chdefrene** [comment]
> new version should fix this issue: 1.6.3 released

Many thanks! Could you please also publish this tag as `latest` on docker hub @spocon ?
