### ISSUE TITLE
Spocon not discoverable after some time (1-2 days)

### ISSUE THREAD

**Issue by elagil** [spocon/spocon#9]
**Describe the bug**
Spocon disappears from the spotify discovery after some time (running on Raspberry Pi 4). Therefore, I cannot connect or play music.

**To Reproduce**
1. Run Spocon
2. Wait 1-2 days

**Expected behavior**
Remain discoverable

**Additional context**
Here is the log output of the spocon service up to the crash:
```
Mar 05 11:42:34 raspberrypi java[10613]: 2020-03-05 11:42:34 FATAL Session:941 - Failed reading packet!
Mar 05 11:42:34 raspberrypi java[10613]: java.io.EOFException
Mar 05 11:42:34 raspberrypi java[10613]:         at java.base/java.io.DataInputStream.readFully(DataInputStream.java:202)
Mar 05 11:42:34 raspberrypi java[10613]:         at java.base/java.io.DataInputStream.readFully(DataInputStream.java:170)
Mar 05 11:42:34 raspberrypi java[10613]:         at xyz.gianlu.librespot.crypto.CipherPair.receiveEncoded(CipherPair.java:60)
Mar 05 11:42:34 raspberrypi java[10613]:         at xyz.gianlu.librespot.core.Session$Receiver.run(Session.java:933)
Mar 05 11:42:34 raspberrypi java[10613]:         at java.base/java.lang.Thread.run(Thread.java:834)
Mar 05 11:42:45 raspberrypi java[10613]: 2020-03-05 11:42:45 INFO  Session:275 - Connected successfully!
Mar 05 11:42:45 raspberrypi java[10613]: 2020-03-05 11:42:45 INFO  Session:580 - Re-authenticated as xxxxxxxxxx!
Mar 05 11:42:45 raspberrypi java[10613]: 2020-03-05 11:42:45 INFO  Session:1000 - Skipping SecretBlock
Mar 05 11:42:45 raspberrypi java[10613]: 2020-03-05 11:42:45 INFO  Session:979 - Received LicenseVersion: 0
Mar 05 11:42:45 raspberrypi java[10613]: 2020-03-05 11:42:45 INFO  Session:969 - Received CountryCode: DE
Mar 05 11:42:45 raspberrypi java[10613]: 2020-03-05 11:42:45 INFO  Session:1000 - Skipping ProductInfo
Mar 05 11:42:45 raspberrypi java[10613]: 2020-03-05 11:42:45 INFO  Session:1000 - Skipping LegacyWelcome
Mar 05 11:42:45 raspberrypi java[10613]: 2020-03-05 11:42:45 INFO  Session:1000 - Skipping UnknownData_AllZeros
Mar 05 11:42:46 raspberrypi java[10613]: 2020-03-05 11:42:46 TRACE MercuryClient:176 - Handling packet, cmd: MercuryEvent, seq: -3745306040111988736, flags: 1, parts: 1
Mar 05 11:42:46 raspberrypi java[10613]: 2020-03-05 11:42:46 DEBUG MercuryClient:209 - Couldn't dispatch Mercury event {seq: -3745306040111988736, uri: hm://pusher/v1/connections/xxxxxxxxxx
Mar 05 11:42:46 raspberrypi java[10613]: 2020-03-05 11:42:46 DEBUG Session:983 - Received 0x10: xxxxxxxxxx
Mar 05 11:42:46 raspberrypi java[10613]: 2020-03-05 11:42:46 INFO  Session:936 - Skipping unknown command {cmd: 0x75, payload: 000000}
Mar 05 15:36:52 raspberrypi java[10613]: 2020-03-05 15:36:52 WARN  Session:952 - Socket timed out. Reconnecting...
Mar 05 15:36:53 raspberrypi java[10613]: 2020-03-05 15:36:53 INFO  Session:275 - Connected successfully!
Mar 05 15:36:53 raspberrypi java[10613]: 2020-03-05 15:36:53 INFO  Session:580 - Re-authenticated as xxxxxxxxxx!
Mar 05 15:36:53 raspberrypi java[10613]: 2020-03-05 15:36:53 INFO  Session:1000 - Skipping SecretBlock
Mar 05 15:36:53 raspberrypi java[10613]: 2020-03-05 15:36:53 INFO  Session:979 - Received LicenseVersion: 0
Mar 05 15:36:53 raspberrypi java[10613]: 2020-03-05 15:36:53 INFO  Session:969 - Received CountryCode: DE
Mar 05 15:36:53 raspberrypi java[10613]: 2020-03-05 15:36:53 INFO  Session:1000 - Skipping ProductInfo
Mar 05 15:36:53 raspberrypi java[10613]: 2020-03-05 15:36:53 INFO  Session:1000 - Skipping LegacyWelcome
Mar 05 15:36:53 raspberrypi java[10613]: 2020-03-05 15:36:53 INFO  Session:1000 - Skipping UnknownData_AllZeros
Mar 05 15:36:54 raspberrypi java[10613]: 2020-03-05 15:36:54 TRACE MercuryClient:176 - Handling packet, cmd: MercuryEvent, seq: -4587197695453560832, flags: 1, parts: 1
Mar 05 15:36:54 raspberrypi java[10613]: 2020-03-05 15:36:54 DEBUG MercuryClient:209 - Couldn't dispatch Mercury event {seq: -4587197695453560832, uri: hm://pusher/v1/connections/xxxxxxxxxx
Mar 05 15:36:54 raspberrypi java[10613]: 2020-03-05 15:36:54 DEBUG Session:983 - Received 0x10: xxxxxxxxxx
Mar 05 15:36:54 raspberrypi java[10613]: 2020-03-05 15:36:54 INFO  Session:936 - Skipping unknown command {cmd: 0x75, payload: 000000}
```

I blanked some of the long hex strings, because I do not know if it is required to keep them private.

**Comment by devgianlu** [comment]
Which version are you running?

**Comment by elagil** [comment]
I am not sure, only librespot-java-core is reported:

```
● spocon.service - SpoCon
   Loaded: loaded (/lib/systemd/system/spocon.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-03-05 22:11:16 GMT; 8h ago
  Process: 30286 ExecStartPre=/bin/sh -c until ping -c1 spotify.com; do sleep 5; done; (code=exited, status=0/SUCCESS)
 Main PID: 30289 (java)
    Tasks: 26 (limit: 1599)
   Memory: 66.4M
   CGroup: /system.slice/spocon.service
           └─30289 /usr/bin/java -jar /opt/spocon/librespot-java-core-v1.2.2.jar
```

It should be the latest one, no upgrade is offered.

**Comment by devgianlu** [comment]
Looks like a reconnection issue, the websocket connection probably dropped, but didn't restart. I don't have any mean to debug this until it happens on my system.

Always keep the latest version as each release always contains some improvements in this direction.

**Comment by spocon** [comment]
@elagil Release 1.3.0 is out with a lot of fixes, try out if it fixes your problem as well. Closing this ticket

FYI the publication of the new release can take up to 3 hours until they show up in your update
